-- Tables for Ivonei Eletrotécnico landing page
-- Matches fields used in index.html (downloads library + contact form / admin)

-- ---------------------------------------------------------------------------
-- downloads
-- ---------------------------------------------------------------------------
create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  type text not null default 'pdf',
  url text not null,
  size text not null default 'Vária',
  downloads integer not null default 0,
  date date not null default (current_date),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint downloads_downloads_non_negative check (downloads >= 0)
);

create index if not exists downloads_date_idx on public.downloads (date desc);
create index if not exists downloads_name_idx on public.downloads (name);

comment on table public.downloads is 'Public download library items shown on the landing page';

-- ---------------------------------------------------------------------------
-- contact_requests
-- ---------------------------------------------------------------------------
create table if not exists public.contact_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null default '',
  email text not null default '',
  service text not null default '',
  message text not null default '',
  status text not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contact_requests_status_check check (status in ('new', 'contacted', 'closed'))
);

create index if not exists contact_requests_created_at_idx
  on public.contact_requests (created_at desc);

create index if not exists contact_requests_status_idx
  on public.contact_requests (status);

comment on table public.contact_requests is 'Contact / quote requests from the landing form';

-- ---------------------------------------------------------------------------
-- updated_at helper
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists downloads_set_updated_at on public.downloads;
create trigger downloads_set_updated_at
  before update on public.downloads
  for each row execute function public.set_updated_at();

drop trigger if exists contact_requests_set_updated_at on public.contact_requests;
create trigger contact_requests_set_updated_at
  before update on public.contact_requests
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Atomic download counter (used by increment action)
-- ---------------------------------------------------------------------------
create or replace function public.increment_download_count(p_id bigint)
returns public.downloads
language plpgsql
security definer
set search_path = public
as $$
declare
  row public.downloads;
begin
  update public.downloads
  set downloads = downloads + 1
  where id = p_id
  returning * into row;

  if row.id is null then
    raise exception 'download not found: %', p_id;
  end if;

  return row;
end;
$$;

grant execute on function public.increment_download_count(bigint) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- Public read for downloads; public insert for contact requests.
-- Admin mutations (update/delete downloads, delete requests) require a
-- future authenticated admin role — for now also allow via anon for
-- parity with the previous Netlify/localStorage admin panel.
-- Tighten these policies after wiring real Supabase Auth.
-- ---------------------------------------------------------------------------
alter table public.downloads enable row level security;
alter table public.contact_requests enable row level security;

drop policy if exists "downloads_select_public" on public.downloads;
create policy "downloads_select_public"
  on public.downloads for select
  to anon, authenticated
  using (true);

drop policy if exists "downloads_insert_public" on public.downloads;
create policy "downloads_insert_public"
  on public.downloads for insert
  to anon, authenticated
  with check (true);

drop policy if exists "downloads_update_public" on public.downloads;
create policy "downloads_update_public"
  on public.downloads for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "downloads_delete_public" on public.downloads;
create policy "downloads_delete_public"
  on public.downloads for delete
  to anon, authenticated
  using (true);

drop policy if exists "contact_requests_select_public" on public.contact_requests;
create policy "contact_requests_select_public"
  on public.contact_requests for select
  to anon, authenticated
  using (true);

drop policy if exists "contact_requests_insert_public" on public.contact_requests;
create policy "contact_requests_insert_public"
  on public.contact_requests for insert
  to anon, authenticated
  with check (true);

drop policy if exists "contact_requests_delete_public" on public.contact_requests;
create policy "contact_requests_delete_public"
  on public.contact_requests for delete
  to anon, authenticated
  using (true);

drop policy if exists "contact_requests_update_public" on public.contact_requests;
create policy "contact_requests_update_public"
  on public.contact_requests for update
  to anon, authenticated
  using (true)
  with check (true);
