-- Fix: INSERT into downloads fails with
--   null value in column "id" of relation "downloads" violates not-null constraint
-- Live table has bigint PK without IDENTITY/DEFAULT (CREATE TABLE IF NOT EXISTS
-- skipped the original identity definition when the table already existed).

do $$
declare
  col_type text;
  col_default text;
  is_identity text;
  max_id bigint;
begin
  select c.data_type, c.column_default, c.is_identity
  into col_type, col_default, is_identity
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'downloads'
    and c.column_name = 'id';

  if col_type is null then
    raise notice 'public.downloads.id not found — skip';
    return;
  end if;

  -- UUID column without default → gen_random_uuid()
  if col_type = 'uuid' then
    if col_default is null then
      alter table public.downloads
        alter column id set default gen_random_uuid();
    end if;
    return;
  end if;

  -- bigint/integer: ensure IDENTITY or sequence-backed DEFAULT
  if col_type in ('bigint', 'integer', 'smallint') then
    if is_identity in ('YES', 'ALWAYS', 'BY DEFAULT') then
      raise notice 'downloads.id already identity — ok';
      return;
    end if;

    if col_default is not null and col_default like 'nextval%' then
      raise notice 'downloads.id already has sequence default — ok';
      return;
    end if;

    -- Prefer GENERATED BY DEFAULT AS IDENTITY (PG 10+)
    begin
      select coalesce(max(id), 0) into max_id from public.downloads;
      execute format(
        'alter table public.downloads alter column id add generated by default as identity (start with %s)',
        greatest(max_id + 1, 1)
      );
      raise notice 'downloads.id set as GENERATED BY DEFAULT AS IDENTITY';
      return;
    exception
      when others then
        raise notice 'IDENTITY alter failed (%), falling back to sequence', SQLERRM;
    end;

    create sequence if not exists public.downloads_id_seq;
    perform setval(
      'public.downloads_id_seq',
      coalesce((select max(id) from public.downloads), 0) + 1,
      false
    );
    alter table public.downloads
      alter column id set default nextval('public.downloads_id_seq');
    alter sequence public.downloads_id_seq owned by public.downloads.id;
    raise notice 'downloads.id default = nextval(downloads_id_seq)';
  end if;
end $$;

comment on column public.downloads.id is 'Primary key with server-side default (identity or sequence)';
